video: adf: Set ADF_MEMBLOCK to boolean
Attempts to build with CONFIG_ADF_MEMBLOCK=m result in the following
build error.

ERROR: "memblock_free" [drivers/video/adf/adf_memblock.ko] undefined!

memblock_free() is marked as __init_memblock, so exporting it seems to be
a bad idea. All other callers are only configurable into the kernel,
so do the same with ADF_MEMBLOCK.

Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit 077be8a752875772589c70299a291070807c8046)
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>